# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: 1.0.11
    - name: Install dependencies
      run: poetry install
    # Missing linting with pylint
    - name: Lint with mypy
      uses: abatilo/actions-poetry@v1.5.0
      run: |
        poetry run mypy .
    - name: Check documentation with pydocstyle
      uses: abatilo/actions-poetry@v1.5.0
      run: |
        poetry run pydocstyle
    - name: Test with pytest
      uses: abatilo/actions-poetry@v1.5.0
      run: |
        poetry run pytest
