# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install -U pip
        pip install poetry
        poetry install
    - name: Install dependencies
      run: poetry install
    - name: Run Pylint
      run: |
        poetry run pylint pos
    - name: Lint with mypy
      run: |
        poetry run mypy --ignore-missing-imports --pretty src/
    - name: Check documentation with pydocstyle
      run: |
        poetry run pydocstyle --match-dir src
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Build with poetry
      run: |
        poetry build
